/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 76a72d2f3fd341401da5fd76b1b416fc)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "Inbox";
  }
  interface Env {
    AI: Ai;
    Inbox: DurableObjectNamespace<import("./src/server").Inbox>;
  }
}
interface Env extends Cloudflare.Env {}
